'use client';

import { useEffect, useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://127.0.0.1:3001';
type PlanId = 'free' | 'go' | 'pro' | 'business';
type Tenant = { id:string; name:string; ownerName:string|null; ownerEmail:string|null; plan:string; planId:PlanId; subscriptionSource:string; subscriptionStatus:string; legal_registered:number; legal_name:string|null; nit:string|null; assignmentNote:string };

export default function PlatformAdmin() {
  const [token,setToken]=useState(''); const [admin,setAdmin]=useState<{name:string;email:string}|null>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [message,setMessage]=useState(''); const [tenants,setTenants]=useState<Tenant[]>([]); const [busy,setBusy]=useState(false);
  const headers=()=>({authorization:`Bearer ${token}`});
  async function load(t=token){ if(!t)return; const r=await fetch(`${API}/platform/tenants`,{headers:{authorization:`Bearer ${t}`}}); if(r.ok){setTenants((await r.json()).tenants)} else {localStorage.removeItem('empre-platform-token');setToken('');setAdmin(null)} }
  useEffect(()=>{const t=localStorage.getItem('empre-platform-token')||''; if(!t)return; setToken(t); fetch(`${API}/platform/me`,{headers:{authorization:`Bearer ${t}`}}).then(async r=>{if(r.ok){setAdmin((await r.json()).admin);load(t)}else localStorage.removeItem('empre-platform-token')}).catch(()=>setMessage('No se pudo conectar con EMPRE.'))},[]);
  async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch(`${API}/platform/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'No se pudo iniciar sesión.');localStorage.setItem('empre-platform-token',d.token);setToken(d.token);setAdmin(d.admin);await load(d.token)}catch(err){setMessage(err instanceof Error?err.message:'Error inesperado.')}finally{setBusy(false)}}
  async function assign(tenant:Tenant,planId:PlanId){setBusy(true);setMessage('');try{const r=await fetch(`${API}/platform/tenants/${tenant.id}/plan`,{method:'PATCH',headers:{...headers(),'content-type':'application/json'},body:JSON.stringify({planId,note:`Asignación manual desde el panel de propietario: ${planId}`})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'No se pudo asignar el plan.');await load();setMessage(`Plan ${planId.toUpperCase()} asignado a ${tenant.name}.`)}catch(err){setMessage(err instanceof Error?err.message:'Error inesperado.')}finally{setBusy(false)}}
  async function logout(){await fetch(`${API}/platform/logout`,{method:'POST',headers:headers()}).catch(()=>{});localStorage.removeItem('empre-platform-token');setToken('');setAdmin(null);setTenants([])}
  if(!token||!admin)return <main className="platform-screen"><section className="platform-card"><span className="section-kicker">CONTROL DE PLATAFORMA</span><h1>Propietario de <span>EMPRE.IA</span></h1><p>Este acceso es exclusivo para administrar empresas, suscripciones manuales y operaciones de la plataforma.</p><form onSubmit={login} className="auth-form"><label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<p className="auth-message">{message}</p>}<button className="primary-button" disabled={busy}>{busy?'Entrando…':'Entrar al panel →'}</button></form><a className="platform-back" href="/">Volver a EMPRE.IA</a></section></main>;
  return <main className="platform-shell"><header className="platform-header"><div><span className="section-kicker">CONTROL DE PLATAFORMA</span><h1>Panel del propietario</h1><p>{admin.name} · {admin.email}</p></div><button className="secondary-button" onClick={logout}>Cerrar sesión</button></header><section className="platform-stats"><div><strong>{tenants.length}</strong><span>Empresas</span></div><div><strong>{tenants.filter(t=>t.planId==='pro').length}</strong><span>Pro</span></div><div><strong>{tenants.filter(t=>t.planId==='business').length}</strong><span>Business</span></div><div><strong>{tenants.filter(t=>t.subscriptionSource==='manual').length}</strong><span>Asignaciones manuales</span></div></section>{message&&<div className="platform-message">{message}</div>}<section className="platform-table"><div className="platform-table-head"><strong>Empresas de EMPRE.IA</strong><span>Asigna o cambia planes manualmente.</span></div><div className="platform-table-scroll"><table><thead><tr><th>Empresa</th><th>Propietario</th><th>Situación</th><th>Plan</th><th>Asignar</th></tr></thead><tbody>{tenants.map(t=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.legal_name||'Sin nombre legal'}</small></td><td><strong>{t.ownerName||'—'}</strong><small>{t.ownerEmail||'—'}</small></td><td>{t.legal_registered?'Registrada':'No registrada'}<small>{t.nit?`NIT ${t.nit}`:'Sin NIT'}</small></td><td><strong>{t.plan}</strong><small>{t.subscriptionSource==='manual'?'Manual':t.subscriptionSource}</small></td><td><select value={t.planId} disabled={busy} onChange={e=>assign(t,e.target.value as PlanId)}><option value="free">Free</option><option value="go">Go</option><option value="pro">Pro</option><option value="business">Business</option></select></td></tr>)}</tbody></table></div></section></main>;
}
